---
# tasks file for ansible-litecoind

- name: create litecoind dir
  file: state=directory path={{ item }}
  with_items:
    - "{{ litecoind_home }}"

- name: copy systemd unit
  template: src="litecoind.service.j2" dest="/etc/systemd/system/litecoind.service"
  notify: restart litecoind

- name: start and enable the service
  systemd:
    name: litecoind
    enabled: yes
    state: started
    daemon_reload: yes

- import_tasks: ltc_exporter.yml
